# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        name: es
        environment:
          cluster.name: test
          discovery.type: single-node
          ELASTIC_PASSWORD: changeme
          xpack.security.enabled: "true"
      - image: docker.elastic.co/kibana/kibana:7.2.0
        name: kb
        environment:
          ELASTICSEARCH_HOSTS: http://es:9200
          ELASTICSEARCH_USERNAME: elastic
          ELASTICSEARCH_PASSWORD: changeme
    working_directory: /go/src/github.com/disaster37/elktools
    steps:
      - checkout
      - run: until $(curl --output /dev/null --silent --head --fail -u elastic:changeme http://kb:5601); do sleep 5; done
      - run: go test ./... -parallel=1
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/disaster37/elktools
    steps:
      - checkout
      - run: go build
  release:
    docker:
      - image: circleci/golang:1.11
        environment:
          - GITHUB_TOKEN: $GITHUB_TOKEN
          - CIRCLE_PROJECT_USERNAME: $CIRCLE_PROJECT_USERNAME
          - CIRCLE_PROJECT_REPONAME: $CIRCLE_PROJECT_REPONAME
          - CIRCLE_TAG: $CIRCLE_TAG
    working_directory: /go/src/github.com/disaster37/elktools
    steps:
      - checkout
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: sed -i 's/app.Version := "develop"/app.Version := "$CIRCLE_TAG"/' elktools-cli.go
      - run: gox -os="linux" -output "dist/elktools_{{.OS}}_{{.Arch}}"
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG dist/
workflows:
  version: 2
  build-workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - release:
          context: Github
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/